chore(ci): check package version match with git tag

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,13 +12,33 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
+  version:
+    runs-on: ubuntu-latest
+    if: startsWith(github.ref, 'refs/tags/')
+    steps:
+      - name: Version
+        uses: sergeysova/jq-action@v2
+        id: version
+        with:
+          cmd: 'jq --raw-output .version package.json'
+      - name: Check
+        run: |
+          _version_package="v${{ steps.version.outputs.value }}"
+          _version_git="${{ github.ref_name }}"
+
+          if [ ! "$_version_package" = "$_version_git" ]; then
+            printf "[ERROR]: Versions do not match --> 'package.json %s' != 'git tag %s'\n" "$_version_package" "$_version_git"
+            exit 1
+          fi
+
   ci:
+    needs: version
+    if: always() && (needs.version.result == 'success' || needs.version.result == 'skipped')
     strategy:
       matrix:
         platform: [ubuntu-latest, macos-latest, windows-latest]
         node-version: [16.x, 18.x]
       fail-fast: true
-
     runs-on: ${{ matrix.platform }}
     steps:
       - name: Checkout repository
@@ -41,9 +61,9 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   release:
-    needs: ci
-    if: needs.ci.result == 'success' && startsWith(github.ref, 'refs/tags/')
     runs-on: ubuntu-latest
+    needs: ci
+    if: startsWith(github.ref, 'refs/tags/') && needs.ci.result == 'success'
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
